id: AE4841A5B
title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage of Zabtik
  Drolchok'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.670537
  last_modified_at: 2022-03-01 04:59:16.670540
