id: AE4841A5B
title: The Dhāraṇī of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.669201
  last_modified_at: 2022-03-01 04:59:16.669204
