id: AE4841A5B
title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara, the
  Glorious Victor, to Avert the Final War'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.662461
  last_modified_at: 2022-03-01 04:59:16.662464
