id: AE4841A5B
title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.710825
  last_modified_at: 2022-03-01 04:59:16.710827
