id: AE4841A5B
title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching from
  the Lama Sangdü'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.609153
  last_modified_at: 2022-03-01 04:59:16.609158
