id: AE4841A5B
title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.708799
  last_modified_at: 2022-03-01 04:59:16.708801
