id: AE4841A5B
title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.646667
  last_modified_at: 2022-03-01 04:59:16.646671
