id: AE4841A5B
title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.625070
  last_modified_at: 2022-03-01 04:59:16.625073
