id: AE4841A5B
title: The Heart of the Transcendent Perfection of Wisdom
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.673558
  last_modified_at: 2022-03-01 04:59:16.673561
