id: AE4841A5B
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.660650
  last_modified_at: 2022-03-01 04:59:16.660652
