id: AE4841A5B
title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and Sacred
  Pledges for Reversing the Disturbances and Agitations of Dark Times In the Form
  of an Aspiration Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.712587
  last_modified_at: 2022-03-01 04:59:16.712590
