id: AE4841A5B
title: Prayer for Dispelling Famine
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.658931
  last_modified_at: 2022-03-01 04:59:16.658933
