id: AE4841A5B
title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.615498
  last_modified_at: 2022-03-01 04:59:16.615506
