id: AE4841A5B
title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.695959
  last_modified_at: 2022-03-01 04:59:16.695962
