id: AE4841A5B
title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.667764
  last_modified_at: 2022-03-01 04:59:16.667767
