id: AE4841A5B
title: The Secret Vajra Knot
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.729431
  last_modified_at: 2022-03-01 04:59:16.729434
