id: AE4841A5B
title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.666446
  last_modified_at: 2022-03-01 04:59:16.666448
