id: AE4841A5B
title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good Actions”
  (Zangchö Mönlam)'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.679741
  last_modified_at: 2022-03-01 04:59:16.679744
