id: AE4841A5B
title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.649935
  last_modified_at: 2022-03-01 04:59:16.649937
