id: AE4841A5B
title: Maitreya's Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.657567
  last_modified_at: 2022-03-01 04:59:16.657570
