id: AE4841A5B
title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.620165
  last_modified_at: 2022-03-01 04:59:16.620168
