id: AE4841A5B
title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of the Vast
  Expanse
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.702758
  last_modified_at: 2022-03-01 04:59:16.702761
