id: AE4841A5B
title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the Omniscient
  Buddha''s Teachings'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.725793
  last_modified_at: 2022-03-01 04:59:16.725796
