id: AE4841A5B
title: The Prayer of the Words of Truth
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.706020
  last_modified_at: 2022-03-01 04:59:16.706023
