id: AE4841A5B
title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.691861
  last_modified_at: 2022-03-01 04:59:16.691864
