id: AE4841A5B
title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration for
  the Flourishing and Spread of the Ancient Translation Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.744700
  last_modified_at: 2022-03-01 04:59:16.744703
