id: AE4841A5B
title: Brief Sukhāvatī Aspiration
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.618631
  last_modified_at: 2022-03-01 04:59:16.618634
