id: AE4841A5B
title: A Brief Practice for Paying Homage and Making Offerings to the Buddha together
  with his retinue of Arhats
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.604843
  last_modified_at: 2022-03-01 04:59:16.604851
