id: AE4841A5B
title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.732780
  last_modified_at: 2022-03-01 04:59:16.732782
