id: AE4841A5B
title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:59:16.607294
  last_modified_at: 2022-03-01 04:59:16.607298
